# Generated by Django 5.1.5 on 2026-04-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suit',
            name='collection',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard'), ('Budget', 'Budget')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='suit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suits/'),
        ),
        migrations.AddField(
            model_name='suit',
            name='rental_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='days_requested',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suit',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='suit',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
