# Generated by Django 5.1.5 on 2026-04-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_suit_collection_suit_image_suit_rental_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='suit',
        ),
        migrations.AlterField(
            model_name='suit',
            name='collection',
            field=models.CharField(default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='suit',
            name='color',
            field=models.CharField(default='Black', max_length=30),
        ),
        migrations.AlterField(
            model_name='suit',
            name='size',
            field=models.CharField(default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='suit',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='SuitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('days_requested', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.suit')),
            ],
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='RentalRequest',
        ),
    ]
