# Generated by Django 5.1.5 on 2026-04-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_rentalrequest_suit_alter_suit_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suit',
            name='collection',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard'), ('Budget', 'Budget')], default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='suit',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=20),
        ),
    ]
