# Generated by Django 6.0.4 on 2026-04-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_suit_collection_alter_suit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitrequest',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suitrequest',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
