# Generated by Django 5.1.5 on 2026-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_suitrequest_is_notified_alter_suitrequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitrequest',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
