# Generated by Django 5.1.5 on 2026-04-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_suitrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitrequest',
            name='rental_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suitrequest',
            name='days_requested',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='suitrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Active', 'Active'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
