# Generated by Django 5.1.5 on 2026-04-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_suitrequest_rental_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitrequest',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
