# Generated by Django 5.1.5 on 2026-04-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_suit_description_suitrequest_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
