# Generated by Django 5.2 on 2026-06-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_cashier',
            field=models.BooleanField(default=False),
        ),
    ]
