# Generated by Django 5.2 on 2026-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitrequest',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
