# Generated by Django 5.2 on 2026-06-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_suitrequest_is_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitrequest',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
