# Generated by Django 5.1.5 on 2026-06-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_expense_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_reception',
            field=models.BooleanField(default=False),
        ),
    ]
