# Generated by Django 6.0.4 on 2026-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suitrequest',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suitrequest',
            name='rent_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
