# Generated by Django 6.0.4 on 2026-07-13 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_staff_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dry_cleanings', to='rental.suit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
