# Generated by Django 5.1.5 on 2026-07-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0028_drycleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='drycleaning',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected by Admin')], default='pending', max_length=20),
        ),
    ]
