# Generated by Django 6.0.4 on 2026-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_drycleaning_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suit',
            name='item_type',
            field=models.CharField(blank=True, default='suits', max_length=20),
        ),
    ]
