from django.urls import path
from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("admin-login/", views.login_view, name="admin_login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("admin-desk/", views.dashboard, name="admin_desk"),
    path("cashier-dashboard/", views.cashier_dashboard, name="cashier_dashboard"),
    path("reception-dashboard/", views.reception_dashboard, name="reception_dashboard"),
    path("reception-desk/", views.reception_reception, name="reception_desk"),
    path("requests/", views.requests_page, name="requests"),
    path("pending-requests/", views.requests_page, name="pending_requests"),
    
    # Maareynta Codsiyada
    path("approve/<int:req_id>/", views.approve_request, name="approve_request"),
    path("approve-and-rent/<int:req_id>/", views.approve_request, name="approve_and_rent"),
    path("reject/<int:req_id>/", views.reject_request, name="reject_request"),
    path("return/<int:req_id>/", views.return_suit, name="return_suit"),
    path("return-view/<int:request_id>/", views.return_suit_view, name="return_view"),
    path("return-audit/<int:request_id>/", views.return_suit_audit_view, name="return_audit"),
    path("process-return/", views.process_return, name="process_return"),
    path("process-reservation/", views.process_reservation, name="process_reservation"),
    path("receipt/<int:req_id>/", views.receipt_view, name="receipt"),
    path("reception/receipt/<int:req_id>/", views.reception_recept_sheet, name="reception_recept_sheet"),
    # Kani waa qaybtii dhimnayd

    # Codsiga Macmiilka
    path("request/<int:suit_id>/", views.request_suit, name="request_suit"),
    path("request-form/<int:suit_id>/", views.request_suit, name="request_form"),  # Alias for request_suit
    path("book-suit/", views.book_suit, name="book_suit"),
    path("suits/", views.all_suits, name="all_suits"),
    path("service/", views.service_page, name="service_page"),
    path("contact/", views.contact_page, name="contact_page"),
    path("about/", views.about_page, name="about_page"),
    
    # Suit Management
    path("edit-suit/<int:suit_id>/", views.edit_suit, name="edit_suit"),
    path("delete-suit/<int:suit_id>/", views.delete_suit, name="delete_suit"),
    path('suits/add/', views.add_suit, name='add_suit'),
    path('add-suit/', views.add_suit, name='add_suit_alternate'),
    # Backwards-compatible aliases used by the admin inventory template/modal
    path('inventory/add/', views.add_suit, name='inventory_add_suit'),
    path('inventory/', views.inventory_management, name='inventory'),
    path('inventory/', views.inventory_management, name='admin_inventory'),
    path('export-inventory/', views.export_inventory, name='export_inventory'),
    path('admin-profile/', views.admin_profile, name='admin_profile'),
    path('settings/', views.admin_profile, name='settings'),
    path('customers/', views.customers, name='customers'),
    path('reports/', views.reports, name='reports'),
    path('reports/expense-entry/', views.expense_entry, name='expense_entry'),
    path('payments/', views.payments, name='payments'),
    path('admin/payments/', views.admin_payments, name='admin_payments'),
    path('payments/admin/', views.admin_payments, name='admin_payments_legacy'),
    path('reception/payments/', views.reception_payments, name='reception_payments'),
    path('reception-payments/', views.reception_payments, name='reception_payments_legacy'),
    path('add-expense/', views.add_expense, name='add_expense'),
    path('reception-inventory/', views.reception_inventory, name='reception_inventory'),
    path('reception-requests/', views.reception_requests, name='reception_requests'),
    path('reception-home/', views.reception_home, name='reception_home'),
    path('reception-profile/', views.reception_profile, name='reception_profile'),
    path('reception-reception/', views.reception_reception, name='reception_reception'),
    path('admin-booking/', views.admin_booking, name='admin_booking'),
    path('reception-suits/', views.all_suits_reception, name='all_suits_reception'),
    path('reception/customer-search/', views.customer_search, name='customer_search'),
    path('create-rental/', views.create_rental, name='create_rental'),
    path('create-booking/', views.create_rental, name='create_booking'),
    path('customer-detail/<str:customer_name>/', views.customer_detail, name='customer_detail'),
    path('customer-detail/user/<int:user_id>/', views.customer_detail_by_user, name='customer_detail_by_user'),
    path('new-rent/<int:user_id>/', views.new_rent_for_customer, name='new_rent_for_customer'),
    path('send-return-reminder/<int:req_id>/', views.send_return_reminder, name='send_return_reminder'),
    path('reception-reports/', views.reception_reports, name='reception_reports'),
    path('reception-payments/', views.reception_payments, name='reception_payments'),
    path('dry-cleaning/', views.dry_cleaning_page, name='dry_cleaning'),
    path('dry-cleaning/page/', views.dry_cleaning_page, name='dry_cleaning_page'),
    path('dry-cleaning/mark-paid/<int:entry_id>/', views.mark_dry_cleaning_paid, name='mark_cleaning_paid'),
    path('dry-cleaning/ledger/', views.dry_cleaning_ledger, name='dry_cleaning_ledger'),
    path('dry-cleaning/backlog/', views.laundry_backlog_view, name='laundry_backlog'),
    path('payments/record/', views.record_payment, name='record_payment'),
    path('payments/receipt/<int:payment_id>/', views.payment_receipt, name='payment_receipt'),
    path('payments/receipt/<int:payment_id>/print/', views.payment_receipt, name='payment_receipt_print'),
    path('payments/refund/', views.process_refund, name='process_refund'),
    path('payments/<int:payment_id>/mark-paid/', views.mark_payment_as_paid, name='mark_payment_as_paid'),
    path('rentals/<int:rental_id>/apply-discount/', views.apply_discount, name='apply_discount'),
    path('payments/export/', views.export_payments, name='export_payments'),
    path('download-report/', views.download_report, name='download_report'),
    path('payments/pending/', views.pending_balances, name='pending_balances'),
    path('payments/deposits/', views.deposit_management, name='deposit_management'),
    path('payments/report/daily/', views.daily_report, name='daily_report'),
    path('reception/shift/close/', views.close_shift, name='close_shift'),
    path('reception-send-sms/<int:req_id>/', views.reception_send_sms, name='reception_send_sms'),
    # POST endpoint for deleting suits from the inventory modal
    path('inventory/delete/', views.inventory_delete_suit, name='inventory_delete_suit'),
    path('pay/<int:req_id>/', views.pay_request, name='pay_request'),
    path('stripe-success/<int:req_id>/', views.stripe_success, name='stripe_success'),
    path('stripe-cancel/<int:req_id>/', views.stripe_cancel, name='stripe_cancel'),
    
    # Customer Authentication
    path('register/', views.register_view, name='register'),
    path('login/', views.customer_login, name='customer_login'),
    path('customer-logout/', views.customer_logout, name='customer_logout'),
    path('my-bookings/', views.customer_history, name='customer_history'),
    path('toggle-favorite/<int:suit_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/mark-read/<int:notif_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('delete-notification/<int:notif_id>/', views.delete_notification, name='delete_notification'),
    path('send-notifications/', views.send_notifications, name='send_notifications'),
    
    # User Management (Admin Only)
    path('manage-users/', views.manage_users, name='manage_users'),
    path('add-staff/', views.add_staff, name='add_staff'),
    path('add-payroll/', views.add_payroll, name='add_payroll'),
    path('create-cashier/', views.create_cashier, name='create_cashier'),
    path('reception-form/', views.reception_form, name='reception_form'),
    path('create-reception/', views.create_reception, name='create_reception'),
    path('toggle-reception-role/<int:user_id>/', views.toggle_reception_role, name='toggle_reception_role'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('toggle-user-active/<int:user_id>/', views.toggle_user_active, name='toggle_user_active'),
    
    # Inventory Management Views
    path('inventory/add-suit/', views.add_suit_view, name='add_suit_new'),
    path('inventory/add-suit/', views.add_suit_view, name='reception_add_item'),
    path('inventory/edit-suit/<int:suit_id>/', views.edit_suit_view, name='edit_suit_new'),
    path('inventory/edit-suit/<int:suit_id>/', views.edit_suit_view, name='inventory_edit_suit'),
    path('inventory/delete-suit/<int:suit_id>/', views.delete_suit_view, name='delete_suit_new'),
    path('inventory/suit/<int:suit_id>/status/', views.update_suit_status, name='update_suit_status'),
    path('inventory/suit/<int:suit_id>/retire/', views.retire_suit, name='retire_suit'),
    path('inventory/suit/<int:suit_id>/restore/', views.restore_suit, name='restore_suit'),
    path('inventory/suit/<int:suit_id>/', views.suit_profile, name='suit_profile_short'),
    path('inventory/suit/<int:suit_id>/profile/', views.suit_profile, name='suit_profile'),
    # JSON API for inventory modal
    path('api/suits/<int:suit_id>/', views.suit_api_detail, name='suit_api_detail'),
    # Status workflow transitions
    path('suit/<int:suit_id>/mark-dry-cleaning/', views.mark_suit_as_dry_cleaning, name='mark_dry_cleaning'),
    path('suit/<int:suit_id>/mark-available/', views.mark_suit_as_available, name='mark_available'),
]
